version: "3.9"

services:
  frontend:
    build: ./frontend
    networks:
      - main
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    networks:
      - main
    ports:
      - "3030:3030"

networks:
  main:
    driver: bridge